apiVersion: v1
kind: Service
metadata:
  name: webhook-emailer
  namespace: webhook-emailer
  labels:
    app: webhook-emailer
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: webhook-emailer
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-emailer
  namespace: webhook-emailer
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: webhook-emailer
  template:
    metadata:
      labels:
        app: webhook-emailer
    spec:
      containers:
        - name: listener
          image: webhook-emailler
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: listener
  namespace: webhook-emailer
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - api.example.com
      secretName: api-example-com
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webhook-emailer
                port:
                  number: 8080
